spring.application.name=lyratech_backend

spring.datasource.url=jdbc:mysql://localhost:3306/lyra_tech

spring.datasource.username=root

spring.datasource.password=Manada@001

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=8080